spring:
  data:
    mongodb:
      uri: 'mongodb://manthan:G*ZKAg{8vTcHy7Rs@18.217.105.222:27017/reviews'
---
# Local development environment
spring:
  profiles: default
server:
  port: 5000
  
      